### ISSUE TITLE
Publish v1.5.0 to NPM

### ISSUE THREAD

**Issue by pdroll** [thomasbrueggemann/node-servertiming#6]
The latest commits that implement the most current format for the ServerTiming header are great! Nice work on getting that done!

It looks like the latest version that [NPM has is v1.4.0](https://www.npmjs.com/package/servertiming), which is before the updates to the header format. Could you publish the latest to NPM so we can easily make use of your latest work? 

Thanks!

**Comment by thomasbrueggemann** [comment]
@pdroll Good point, thanks! I will publish the update as soon as I have regained access to my NPM account via their wonderful support team. I'll close this issue, when the update is done.

**Comment by thomasbrueggemann** [comment]
There you go :-) https://www.npmjs.com/package/servertiming/v/1.5.0

**Comment by pdroll** [comment]
Fantastic, thank you!
